apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: stock
  namespace: knative-stock
spec:
  template:
    metadata:
      name: stock-v1
    spec:
      containers:
        - image: gandhicloud/knative-stock:v1
          imagePullPolicy: Always
  traffic:
  - tag: current
    revisionName: stock-v1
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0
